---
- hosts: exporter4
  tasks:
    - name: simple ping
      ping:
    - name: start Docker service
      service:
        name: docker
        state: started
      become: true
    - name: Run Node-Exporter container
      community.general.docker_container:
        name: node-exporter
        image: prom/node-exporter
        ports:
          - "9100:9100"
        restart: yes


