---
- hosts: web-server
  tasks:
    - name: simple ping
      ping:
    - name: start Docker service
      service:
        name: docker
        state: started
      become: true
    - name: Copy Load balancer file
      copy:
        src: default1.conf
        dest: ~/
        mode: '0777'
    - name: Run Nginx container
      community.general.docker_container:
        name: Nginx
        image: nginx
        volumes:
          - ./default1.conf:/etc/nginx/conf.d/default.conf
        ports:
          - "80:80"
        restart: yes
